name: farfor_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.2

  # DI
  get_it: ^7.2.0

  # Local Storage
  hive_flutter: ^1.1.0
  hive: ^2.1.0
  flutter_bloc: ^8.1.1

  # Network
  dio: ^4.0.6

  # Models
  equatable: ^2.0.5

  # обработка ошибок
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0
  add_to_cart_animation: ^1.0.1
  uni_links: ^0.5.1
  firebase_core: ^2.1.1
  firebase_remote_config: ^3.0.3
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # Code Generation
  hive_generator: ^1.1.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/png/
    - assets/
flutter_intl:
  enabled: true
