// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFjbsqbTZCZJjLX8kDYoheyIsalg6gbdY',
    appId: '1:203803586870:android:c043c12751f0ef74300397',
    messagingSenderId: '203803586870',
    projectId: 'farfor-demo',
    storageBucket: 'farfor-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxmyykj9czRvz77Zn5H9rG4vNpsX7IT0',
    appId: '1:203803586870:ios:ab25007b86bc91a1300397',
    messagingSenderId: '203803586870',
    projectId: 'farfor-demo',
    storageBucket: 'farfor-demo.appspot.com',
    androidClientId:
        '203803586870-fnofah0e34efp0vkh9uh7p399anrloep.apps.googleusercontent.com',
    iosClientId:
        '203803586870-cgqlimpkgg0quhj2fmad8qt3hklk6uia.apps.googleusercontent.com',
    iosBundleId: 'com.farfor.demo',
  );
}
